### PR TITLE
Try automatically exporting gerbers

### PR DESCRIPTION
**Pull request by chuckwagoncomputing**
Output looks all right to my untrained eye, but someone else should look it over.
Workflow run: https://github.com/chuckwagoncomputing/hellen88bmw/actions/runs/5536724896/jobs/10104758213
Output: https://github.com/chuckwagoncomputing/hellen88bmw/tree/main/boards/hellen88bmw-c

mentioning for nice Github linking https://github.com/andreika-git/hellen-one/issues/24

### CODE REVIEW

**Comment by chuckwagoncomputing** [comment]
Did you remove the "MY_REPO_PAT" secret from this repo? It looks like the check failed because it's missing.

**Comment by chuckwagoncomputing** [comment]
The workflow would fail on this PR even with it, because the workflow doesn't have the necessary check to not push the new files for a PR.

**Comment by rusefillc** [comment]
> Did you remove the "MY_REPO_PAT" secret from this repo? It looks like the check failed because it's missing.

Nope see https://github.com/rusefi/hellen88bmw/commit/958b80e1b076d814bcd9d98d7ca1bda0755a23ce

See also https://github.com/andreika-git/hellen-one/issues/306

**Comment by rusefillc** [comment]
> The workflow would fail on this PR even with it, because the workflow doesn't have the necessary check to not push the new files for a PR.

Does https://github.com/rusefi/hellen88bmw/commit/fbb7d0da107b401ced88ee1f2b98538db20f2a81 look useful?

**Comment by rusefillc** [comment]
@chuckwagoncomputing please rebase in light of two above mentioned improvements?

**Comment by rusefillc** [comment]
@chuckwagoncomputing looks like stuff was generated!!!

also looks like commit logic needs help :)

**Comment by chuckwagoncomputing** [comment]
I see, it's because this repo has main instead of master.

**Comment by rusefillc** [comment]
> I see, it's because this repo has main instead of master.

thank you!!! https://github.com/rusefi/hellen88bmw/commit/b604a76b1827999cbd0272c6b0378ae026581bf9

**Comment by rusefillc** [comment]
Something got pushed! Let me get in touch with SMEs.

**Pull request merged**
